### ISSUE TITLE
Hodnocení úkolu

### ISSUE THREAD

**Issue by lrolecek** [PetraRockova/PROJEKT-Vizitka#1]
Ahoj.

Koukám na tvůj úkol a vizuálně to vypadá skoro přesně jako zadání, takže úspěch :) Ke kódu mám pár drobných výhrad. Nejsou to žádné brutální chyby, přesto tě ale na konci tohoto textu poprosím, abys chyby opravila, než ti úkol uznám. 

### Section

V HTML máš `<div>` a v něm potom `<section class="box">`. Moc nechápu, proč tam ten div máš, když s ním potom ani v CSS nic neděláš. Zároveň tady trochu nedává smysl ta značka `<section>`, protože ta významově představuje nějakou sekci delšího dokumentu/stránky, a nic takového tady není. 

Myslím, že nejlepší by bylo nechat tam ten `<div>` a přehodit na něj tu třídu _box_ a tu sekci úplně vyhodit. Výsledek bude vizuálně stejný a nebudeš tam mít HTML prvek navíc, který tam významově nedává smysl. Takže jenom:
```
<div class="box">
  <img ..>
  <h1> ...</h1>
  apod.
</div>
```

### Tlačítka

Máš kolem tlačítek značky `<nav>`. To je v pořádku, ale stačí pouze jedna značka `<nav>` kolem obou tlačítek, dělat z každého jednotlivého tlačítka samostatnou navigaci je nesmysl. Zbytečně máš také třídu na těch značkách `<nav>`, kterou používáš jen proto, abys pak mohla v CSS napsat kontextový selektor `.tw a:hover { ... }`. To je úplně zbytečné, protože můžeš ten hover napsat přímo k té třídě, kterou máš přidanou na odkazu.

HTML:
```
<nav>
  <a class="twitter" href="https://twitter.com/">Twitter</a>
  <a class="fb" href="https://www.facebook.com/">Facebook</a>
</nav>
```

CSS:
```
.twitter:hover { ... }
.fb:hover { ... }
```

Také vidím, že ve třídách _.twitter_ a _.fb_ máš spoustu stejných vlastností, které jsou společné pro obě tlačítka. Vzpomeň si na Jirkovu přednášku z minulé středy 10.3., kde o tom mluvil. Vytvoř si nějakou další třídu, například _.button_, do které přesuneš společné vlastnosti. Ve třídách  _.twitter_ a _.fb_ nech pouze vlastnosti specifické pro konkrétní tlačítko (tj. barva pozadí).

## Opravit

Protože jsme se v tomto běhu Kóderky rozhodli, že budeme na úkoly trochu přísnější, tak než ti úkol uznám, poprosím tě o opravu následujícího:

- [x] odstraň z kódu zbytečnou značku `<section>`, třídu _box_ přesuň na `<div>`
- [x] oprav značky `<nav>` kolem tlačítek a oprav CSS pro hover tlačítek
- [x] přesuň společné vlastnosti pro tlačítka do samostatné třídy, kterou pak přidáš na obě tlačítka

Všechny opravené věci tady odškrtni, nezapomeň svoje změny znovu pushnout na GitHub, a potom mi pošli zprávu a já se na to znovu podívám :)

**Comment by PetraRockova** [comment]
Hlásím, že mám opraveno, push proveden.

**Comment by lrolecek** [comment]
Je to super. Úkol máš v classroom započtený. Díky :)
